name: Publish

on:
  release:
    types: [prereleased, released]

defaults:
  run:
    shell: bash

jobs:
  build:
    uses: './.github/workflows/build.yml'
    with:
      ref: ${{ github.event.release.tag_name }}

  upload-release-artifacts:
    name: Upload Release Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          filter: tree:0
          submodules: recursive

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FIND_ASSETS_COMMAND=( find . -type f '(' -false
            -o -path "./thunderstore-build/*/bin/Release/netstandard2.1/dist/*.zip"
            -o -path "./nupkg-build/*/bin/Release/*.nupkg"
            -o -path "./*-binary-*/*/bin/ReleaseApp/*/*/*"
          ')' )
          "${FIND_ASSETS_COMMAND[@]}" -print0 | xargs -0 gh release upload ${{ github.event.release.tag_name }}

  deploy-thunderstore:
    name: Deploy to Thunderstore
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          filter: tree:0
          submodules: recursive

      - name: Download Thunderstore artifact
        uses: actions/download-artifact@v4
        with:
          name: thunderstore-build
          path: Thunderstore

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"

      - name: Restore dotnet tools
        run: |
          dotnet tool restore

      - name: Publish to Thunderstore
        env:
          REPO_THUNDERSTORE_API_TOKEN: ${{ secrets.REPO_THUNDERSTORE_API_TOKEN }}
          LETHAL_COMPANY_THUNDERSTORE_API_TOKEN: ${{ secrets.THUNDERSTORE_API_TOKEN }}
        run: |
          dotnet build -c Release -target:ThunderstorePublish
